version: '3.7'

services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres       # Имя базы данных
      POSTGRES_USER: postgres     # Пользователь базы данных
      POSTGRES_PASSWORD: postgres # Пароль пользователя базы данных
    ports:
      - "5432:5432"               # Открываем порт для доступа
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bot-network

  bot:
    build: .
    container_name: telegram_bot
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_SQL_INIT_SCHEMA_LOCATIONS: classpath:schema.sql
      SPRING_SQL_INIT_MODE: always
    depends_on:
      - postgres
    networks:
      - bot-network

volumes:
  postgres_data:

networks:
  bot-network:
